src/main/java/it/uniroma2/art/loddy/beans/BestChoiceLabelBean.java
package it.uniroma2.art.loddy.beans;

import it.uniroma2.art.loddy.exception.LoddyException;
import it.uniroma2.art.owlart.model.ARTStatement;
import it.uniroma2.art.owlart.models.TripleQueryModelHTTPConnection;
import it.uniroma2.art.owlart.navigation.ARTStatementIterator;
import it.uniroma2.art.owlart.query.QueryLanguage;
import it.uniroma2.art.owlart.utilities.RDFIterators;
import it.uniroma2.art.owlart.vocabulary.RDFS;
import it.uniroma2.art.owlart.vocabulary.SKOS;
import it.uniroma2.art.owlart.vocabulary.SKOSXL;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.faces.context.FacesContext;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BestChoiceLabelBean {
	
	protected static Logger logger = LoggerFactory.getLogger(BestChoiceLabelBean.class);
	
	//managed properties
	private List<String> models; //priority list of desired label models (admitted value: SKOSXL, SKOS, RDFS)
	private List<String> langs; //priority list of desired languages 
	private ConnectionBean connectionBean;
	
	private static final Map<String, String> modelConversionMap;
    static {
    	modelConversionMap = new HashMap<String, String>();
        modelConversionMap.put("SKOSXL", SKOSXL.NAMESPACE);
        modelConversionMap.put("SKOS-XL", SKOSXL.NAMESPACE);
        modelConversionMap.put("SKOS", SKOS.NAMESPACE);
        modelConversionMap.put("RDFS", RDFS.NAMESPACE);
    }
	
	/**
	 * connectionBean property injection.
	 * @param connectionBean
	 */
	public void setConnectionBean(ConnectionBean connectionBean){
		this.connectionBean = connectionBean;
	}
	
	/**
	 * models property injection
	 * @param models
	 */
	public void setModels(List<String> models){
		this.models = models;
	}
	
	/**
	 * langs property injection
	 * @param langs
	 */
	public void setLangs(List<String> langs){
		this.langs = langs;
	}
	
	public String getBestChoiceLabel() throws LoddyException {
		Collection<ARTStatement> graph = doQuery();
		graph = filterGraphForLanguage(graph);
		graph = filterGraphForModel(graph);
		Iterator<ARTStatement> it = graph.iterator();
		if (it.hasNext())
			return it.next().getObject().asLiteral().getLabel();
		else
			return "";
	}
	
	/**
	 * Constructs a graph composed by requested resource (subject), label predicate and label (object). 
	 * @return
	 * @throws LoddyException
	 */
	private Collection<ARTStatement> doQuery() throws LoddyException{
		String requestedResource = connectionBean.getRequestedResourceUri();
		String query = "CONSTRUCT {\n"
			+ "<" + requestedResource + "> ?pred ?label .\n"
			+ "} WHERE { { <" + requestedResource + "> ?pred _:v .\n"
			+ "_:v <" + SKOSXL.LITERALFORM + "> ?label .\n"
			+ "FILTER (?pred = <" + SKOSXL.PREFLABEL + ">)\n"
			+ "} UNION {\n"
			+ "<" + requestedResource + "> ?pred ?label .\n"
			+ "FILTER (?pred = <" + SKOS.PREFLABEL + "> ||\n"
			+ "?pred = <" + RDFS.LABEL + "> ) } }";
		try {
			TripleQueryModelHTTPConnection conn = connectionBean.getConnection();
			it.uniroma2.art.owlart.query.GraphQuery gq = conn.createGraphQuery(
					QueryLanguage.SPARQL, query, "");
			logger.debug("evaluating graph query\n"+query);
			ARTStatementIterator itRes = gq.evaluate(false);
			connectionBean.releaseConnection(conn);
			return RDFIterators.getCollectionFromIterator(itRes);
		} catch (Exception e) {
			e.printStackTrace();
			throw new LoddyException();
		}
	}
	
	private Collection<ARTStatement> filterGraphForLanguage(Collection<ARTStatement> graph){
		Collection<ARTStatement> outGraph = new ArrayList<ARTStatement>();
		boolean langFound = false;
		if (langs != null && langs.size()>0){
			for (String l : langs){ //for every lang
				for (ARTStatement stat : graph){ //for every statement
					if (stat.getObject().asLiteral().getLanguage().equals(l)){ //if the language is the desired one
						outGraph.add(stat); //add the statement to the output graph
						langFound = true; //and make the loop stop, so it doesn't search for other languages
					}
				}
				if (langFound) break;
			}
		} else { //if langs list is not provided or is empty, get language from context
			String l = FacesContext.getCurrentInstance().getExternalContext().getRequestLocale().getLanguage();
			for (ARTStatement stat : graph){ //for every statement
				if (stat.getObject().asLiteral().getLanguage().equals(l)){ //if the language is the desired one
					outGraph.add(stat); //add the statement to the output graph
					langFound = true; //and make the loop stop
				}
			}
		}
		return outGraph;
	}
	
	private Collection<ARTStatement> filterGraphForModel(Collection<ARTStatement> graph){
		Collection<ARTStatement> outGraph = new ArrayList<ARTStatement>();
		boolean modelFound = false;
		if (models == null)
			models = new ArrayList<String>(); //just to avoid NullPointerException if the user doesn't define the list
		for (String m : models){
			for (ARTStatement stat : graph){
				if (stat.getPredicate().getNominalValue().startsWith(modelConversionMap.get(m.toUpperCase()))){
					outGraph.add(stat);
					modelFound = true;
				}
			}
			if (modelFound)
				break;
		}
		return outGraph;
	}
	
	

}

src/main/java/it/uniroma2/art/loddy/beans/ConnectionBean.java
package it.uniroma2.art.loddy.beans;

import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import it.uniroma2.art.owlart.exceptions.ModelAccessException;
import it.uniroma2.art.owlart.exceptions.ModelCreationException;
import it.uniroma2.art.owlart.models.OWLArtModelFactory;
import it.uniroma2.art.owlart.models.TripleQueryModelHTTPConnection;
import it.uniroma2.art.owlart.sesame2impl.factory.ARTModelFactorySesame2Impl;
import it.uniroma2.art.owlart.sesame2impl.models.conf.Sesame2ModelConfiguration;

public class ConnectionBean {
	
	protected static Logger logger = LoggerFactory.getLogger(ConnectionBean.class);
	
	Queue<TripleQueryModelHTTPConnection> connectionPool;

	//managed property
	private String sparqlEndpointURL;
	private String baseURI;
	private String localBaseURI;
	
	private volatile int createdConnection = 0;
	private volatile int availableConnections = 0;
	private volatile int usedConnection = 0;
	
	public ConnectionBean(){
		connectionPool = new ConcurrentLinkedQueue<TripleQueryModelHTTPConnection>();
	}
	
	/*
	 * PostConstructor annotations is used to perform code once the dependency injection are done.
	 * The dependencies are injected after the constuctor and since the operations performed in this
	 * method use injected parameters, they could not be executed in the constructor.
	 */
	@PostConstruct
	public void startPoolHandler(){
		Runnable connStatusRunnable = new Runnable() {
		    public void run() {
		    	availableConnections = connectionPool.size();
		    	usedConnection = createdConnection - availableConnections;
				if (usedConnection < (float) createdConnection / 2){
					try {
						TripleQueryModelHTTPConnection conn = connectionPool.poll();
						conn.disconnect();
						createdConnection--;
					} catch (ModelAccessException e) {
						e.printStackTrace();
					}
				}
		    }
		};
		ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
		executor.scheduleAtFixedRate(connStatusRunnable, 0, 5, TimeUnit.SECONDS);
	}

	
	/**
	 * sparqlEndpointURL property injection
	 * @param sparqlEndpointURL
	 */
	public void setSparqlEndpointURL(String sparqlEndpointURL){
		this.sparqlEndpointURL = sparqlEndpointURL;
	}
	
	public String getSparqlEndpointURL(){
		return sparqlEndpointURL;
	}
	
	/**
	 * baseURI property injection
	 * @param baseURI
	 */
	public void setBaseURI(String baseURI){
		this.baseURI = baseURI;
	}
	
	public String getBaseURI(){
		return baseURI;
	}
	
	/**
	 * localBaseURI property injection
	 * @param localBaseURI
	 */
	public void setLocalBaseURI(String localBaseURI){
		this.localBaseURI = localBaseURI;
	}
	
	public String getLocalBaseURI(){
		return localBaseURI;
	}
	
	/**
	 * Returns the resourceURI involved in the request
	 * @return
	 */
	public String getRequestedResourceUri(){
		HttpServletRequest req = ((HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest());
		String resID = req.getParameter("resID");
		if (resID == null){
			
		}
		return (baseURI + resID);
	}

	public TripleQueryModelHTTPConnection getConnection() throws ModelCreationException{
		TripleQueryModelHTTPConnection conn = connectionPool.poll();
		if (conn == null) //no connection available at the moment => create a new one
			conn = createConnection();
		return conn;
	}
	
	public synchronized void releaseConnection(TripleQueryModelHTTPConnection conn){
		connectionPool.add(conn);
	}
	
	private synchronized TripleQueryModelHTTPConnection createConnection() throws ModelCreationException{
		TripleQueryModelHTTPConnection conn;
		OWLArtModelFactory<Sesame2ModelConfiguration> fact = OWLArtModelFactory.createModelFactory(new ARTModelFactorySesame2Impl());
		conn = fact.loadTripleQueryHTTPConnection(sparqlEndpointURL);
		logger.debug("connected to "+sparqlEndpointURL);
		createdConnection++;
		return conn;
	}
	
	

}

WebContent/collection_skos.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	
<ui:composition template="/WEB-INF/templates/two_column_template.xhtml">

	<ui:define name="header">
		<h:outputLink value="#{formatterBean.formatLink(connectionBean.requestedResourceUri)}">
			<h:outputText value="#{connectionBean.requestedResourceUri}"/>
		</h:outputLink><br/>
		<h:outputText value="#{bestChoiceLabelBean.bestChoiceLabel}"/>
	</ui:define>
	
	<ui:define name="left">

		<ui:repeat var="groupedStat" value="#{graphGrouperCollectionStruct.group()}">
			<h:dataTable var="predicate" value="#{groupedStat.getPredicates()}"
			styleClass="customTable"
			headerClass="customTableHeader"
			rowClasses="customTableOddRow,customTableEvenRow">
				<h:column>
					<f:facet name="header">Property</f:facet>
					<h:outputLink value="#{formatterBean.formatLink(predicate)}">   
						<h:outputText value="#{formatterBean.formatText(predicate)}"/>
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">Value</f:facet> 
					<ui:repeat var="object" value="#{groupedStat.getObjects(predicate)}">
						<h:outputLink rendered="#{formatterBean.isLink(object)}" value="#{formatterBean.formatLink(object)}">
	        				<h:outputText value="#{formatterBean.formatText(object)}"/>
	        			</h:outputLink> 
						<h:outputText rendered="#{!formatterBean.isLink(object)}" value="#{object}" />
						<br/>
					</ui:repeat> 
				</h:column>
			</h:dataTable><br/>
		</ui:repeat>
		
		<!-- COLLECTIONS: LEFT COLUMN : SECOND GROUP -->
	
		<!-- use the same as per concept, as it is only for sorting the remaining predicated putting a few on top
		 TODO: if it is really generic, then rename it so that the name concept is no more inside it 
		-->
		
		<ui:repeat var="groupedStat" value="#{graphGrouperConceptNoStruct.group()}">
			<h:dataTable var="predicate" value="#{groupedStat.getPredicates()}"
			styleClass="customTable"
			headerClass="customTableHeader"
			rowClasses="customTableOddRow,customTableEvenRow">
				<h:column>
					<f:facet name="header">Property</f:facet>
					<h:outputLink value="#{formatterBean.formatLink(predicate)}">   
						<h:outputText value="#{formatterBean.formatText(predicate)}"/>
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">Value</f:facet> 
					<ui:repeat var="object" value="#{groupedStat.getObjects(predicate)}">
						<h:outputLink rendered="#{formatterBean.isLink(object)}" value="#{formatterBean.formatLink(object)}">
	        				<h:outputText value="#{formatterBean.formatText(object)}"/>
	        			</h:outputLink> 
						<h:outputText rendered="#{!formatterBean.isLink(object)}" value="#{object}" />
						<br/>
					</ui:repeat> 
				</h:column>
			</h:dataTable><br/>
		</ui:repeat>
		
	</ui:define>
	
	<ui:define name="right">		
		<h:dataTable var="langNodes" value="#{tupleGrouperLabel.group().getRootNode().getChildren()}"
		styleClass="customTable"
		headerClass="customTableHeader"
		rowClasses="customTableOddRow,customTableEvenRow">
			<h:column>
				<f:facet name="header">prefLabel</f:facet>
				<ui:repeat var="prefTuple" value="#{langNodes.getChildWithValue('http://www.w3.org/2004/02/skos/core#prefLabel').getTuples()}" >
						<h:outputText value="#{prefTuple.getBinding('lexical').getBoundValue().getNominalValue()}"/><br/>
				</ui:repeat>
			</h:column>
			<h:column>
				<f:facet name="header">altLabel</f:facet>
				<ui:repeat var="altTuple" value="#{langNodes.getChildWithValue('http://www.w3.org/2004/02/skos/core#altLabel').getTuples()}" >
						<h:outputText value="#{altTuple.getBinding('lexical').getBoundValue().getNominalValue()}"/><br/>
				</ui:repeat>
			</h:column>
			<h:column>
				<f:facet name="header">Lang</f:facet>
				<h:outputText value="#{langNodes.value}"/>
			</h:column>
		</h:dataTable><br/>
	</ui:define>
	
	<ui:define name="footer">
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('rdf')}">
			<h:outputText value="As RDF/XML"/>
		</h:outputLink>
		 | 
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('ttl')}">
			<h:outputText value="As TURTLE"/>
		</h:outputLink>
		|
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('nt')}">
			<h:outputText value="As NT"/>
		</h:outputLink>
	</ui:define>
	
</ui:composition>

</html> 

WebContent/collection_skosxl.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	
<ui:composition template="/WEB-INF/templates/two_column_template.xhtml">

	<ui:define name="header">
		<h:outputLink value="#{formatterBean.formatLink(connectionBean.requestedResourceUri)}">
			<h:outputText value="#{connectionBean.requestedResourceUri}"/>
		</h:outputLink><br/>
		<h:outputText value="#{bestChoiceLabelBean.bestChoiceLabel}"/>
	</ui:define>
	
	<ui:define name="left">

		<ui:repeat var="groupedStat" value="#{graphGrouperCollectionStruct.group()}">
			<h:dataTable var="predicate" value="#{groupedStat.getPredicates()}"
			styleClass="customTable"
			headerClass="customTableHeader"
			rowClasses="customTableOddRow,customTableEvenRow">
				<h:column>
					<f:facet name="header">Property</f:facet>
					<h:outputLink value="#{formatterBean.formatLink(predicate)}">   
						<h:outputText value="#{formatterBean.formatText(predicate)}"/>
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">Value</f:facet> 
					<ui:repeat var="object" value="#{groupedStat.getObjects(predicate)}">
						<h:outputLink rendered="#{formatterBean.isLink(object)}" value="#{formatterBean.formatLink(object)}">
	        				<h:outputText value="#{formatterBean.formatText(object)}"/>
	        			</h:outputLink> 
						<h:outputText rendered="#{!formatterBean.isLink(object)}" value="#{object}" />
						<br/>
					</ui:repeat> 
				</h:column>
			</h:dataTable><br/>
		</ui:repeat>
		
		<!-- COLLECTIONS: LEFT COLUMN : SECOND GROUP -->
	
		<!-- use the same as per concept, as it is only for sorting the remaining predicated putting a few on top
		 TODO: if it is really generic, then rename it so that the name concept is no more inside it 
		-->
		
		<ui:repeat var="groupedStat" value="#{graphGrouperConceptNoStruct.group()}">
			<h:dataTable var="predicate" value="#{groupedStat.getPredicates()}"
			styleClass="customTable"
			headerClass="customTableHeader"
			rowClasses="customTableOddRow,customTableEvenRow">
				<h:column>
					<f:facet name="header">Property</f:facet>
					<h:outputLink value="#{formatterBean.formatLink(predicate)}">   
						<h:outputText value="#{formatterBean.formatText(predicate)}"/>
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">Value</f:facet> 
					<ui:repeat var="object" value="#{groupedStat.getObjects(predicate)}">
						<h:outputLink rendered="#{formatterBean.isLink(object)}" value="#{formatterBean.formatLink(object)}">
	        				<h:outputText value="#{formatterBean.formatText(object)}"/>
	        			</h:outputLink> 
						<h:outputText rendered="#{!formatterBean.isLink(object)}" value="#{object}" />
						<br/>
					</ui:repeat> 
				</h:column>
			</h:dataTable><br/>
		</ui:repeat>
		
	</ui:define>
	
	<ui:define name="right">		
		<h:dataTable var="langNodes" value="#{tupleGrouperLabel.group().getRootNode().getChildren()}"
		styleClass="customTable"
		headerClass="customTableHeader"
		rowClasses="customTableOddRow,customTableEvenRow">
			<h:column>
				<f:facet name="header">prefLabel</f:facet>
				<ui:repeat var="prefTuple" value="#{langNodes.getChildWithValue('http://www.w3.org/2008/05/skos-xl#prefLabel').getTuples()}" >
					<h:outputLink value="#{formatterBean.formatLink(prefTuple.getBinding('uri').getBoundValue().getNominalValue())}">
						<h:outputText value="#{prefTuple.getBinding('lexical').getBoundValue().getNominalValue()}"/><br/>
					</h:outputLink>
				</ui:repeat>
			</h:column>
			<h:column>
				<f:facet name="header">altLabel</f:facet>
				<ui:repeat var="altTuple" value="#{langNodes.getChildWithValue('http://www.w3.org/2008/05/skos-xl#altLabel').getTuples()}" >
					<h:outputLink value="#{formatterBean.formatLink(altTuple.getBinding('uri').getBoundValue().getNominalValue())}">
						<h:outputText value="#{altTuple.getBinding('lexical').getBoundValue().getNominalValue()}"/><br/>
					</h:outputLink>
				</ui:repeat>
			</h:column>
			<h:column>
				<f:facet name="header">Lang</f:facet>
				<h:outputText value="#{langNodes.value}"/>
			</h:column>
		</h:dataTable><br/>
	</ui:define>
	
	<ui:define name="footer">
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('rdf')}">
			<h:outputText value="As RDF/XML"/>
		</h:outputLink>
		 | 
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('ttl')}">
			<h:outputText value="As TURTLE"/>
		</h:outputLink>
		|
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('nt')}">
			<h:outputText value="As NT"/>
		</h:outputLink>
	</ui:define>
	
</ui:composition>

</html> 

WebContent/concept_scheme_skos.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	
<ui:composition template="/WEB-INF/templates/two_column_template.xhtml">

	<ui:define name="header">
		<h:outputLink value="#{formatterBean.formatLink(connectionBean.requestedResourceUri)}">
			<h:outputText value="#{connectionBean.requestedResourceUri}"/>
		</h:outputLink><br/>
		<h:outputText value="#{bestChoiceLabelBean.bestChoiceLabel}"/>
	</ui:define>
	
	<ui:define name="left">

		<ui:repeat var="groupedStat" value="#{graphGrouperConceptSchemeStruct.group()}">
			<h:dataTable var="predicate" value="#{groupedStat.getPredicates()}"
			styleClass="customTable"
			headerClass="customTableHeader"
			rowClasses="customTableOddRow,customTableEvenRow">
				<h:column>
					<f:facet name="header">Property</f:facet>
					<h:outputLink value="#{formatterBean.formatLink(predicate)}">   
						<h:outputText value="#{formatterBean.formatText(predicate)}"/>
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">Value</f:facet> 
					<ui:repeat var="object" value="#{groupedStat.getObjects(predicate)}">
						<h:outputLink rendered="#{formatterBean.isLink(object)}" value="#{formatterBean.formatLink(object)}">
	        				<h:outputText value="#{formatterBean.formatText(object)}"/>
	        			</h:outputLink> 
						<h:outputText rendered="#{!formatterBean.isLink(object)}" value="#{object}" />
						<br/>
					</ui:repeat> 
				</h:column>
			</h:dataTable><br/>
		</ui:repeat>
		
		<!-- CONCEPT SCHEMES: LEFT COLUMN : SECOND GROUP -->
	
		<!-- use the same as per concept, as it is only for sorting the remaining predicated putting a few on top
		 TODO: if it is really generic, then rename it so that the name concept is no more inside it 
		-->
		
		<ui:repeat var="groupedStat" value="#{graphGrouperConceptNoStruct.group()}">
			<h:dataTable var="predicate" value="#{groupedStat.getPredicates()}"
			styleClass="customTable"
			headerClass="customTableHeader"
			rowClasses="customTableOddRow,customTableEvenRow">
				<h:column>
					<f:facet name="header">Property</f:facet>
					<h:outputLink value="#{formatterBean.formatLink(predicate)}">   
						<h:outputText value="#{formatterBean.formatText(predicate)}"/>
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">Value</f:facet> 
					<ui:repeat var="object" value="#{groupedStat.getObjects(predicate)}">
						<h:outputLink rendered="#{formatterBean.isLink(object)}" value="#{formatterBean.formatLink(object)}">
	        				<h:outputText value="#{formatterBean.formatText(object)}"/>
	        			</h:outputLink> 
						<h:outputText rendered="#{!formatterBean.isLink(object)}" value="#{object}" />
						<br/>
					</ui:repeat> 
				</h:column>
			</h:dataTable><br/>
		</ui:repeat>
		
	</ui:define>
	
	<ui:define name="right">		
		<h:dataTable var="langNodes" value="#{tupleGrouperLabel.group().getRootNode().getChildren()}"
		styleClass="customTable"
		headerClass="customTableHeader"
		rowClasses="customTableOddRow,customTableEvenRow">
			<h:column>
				<f:facet name="header">prefLabel</f:facet>
				<ui:repeat var="prefTuple" value="#{langNodes.getChildWithValue('http://www.w3.org/2004/02/skos/core#prefLabel').getTuples()}" >
						<h:outputText value="#{prefTuple.getBinding('lexical').getBoundValue().getNominalValue()}"/><br/>
				</ui:repeat>
			</h:column>
			<h:column>
				<f:facet name="header">altLabel</f:facet>
				<ui:repeat var="altTuple" value="#{langNodes.getChildWithValue('http://www.w3.org/2004/02/skos/core#altLabel').getTuples()}" >
						<h:outputText value="#{altTuple.getBinding('lexical').getBoundValue().getNominalValue()}"/><br/>
				</ui:repeat>
			</h:column>
			<h:column>
				<f:facet name="header">Lang</f:facet>
				<h:outputText value="#{langNodes.value}"/>
			</h:column>
		</h:dataTable><br/>
	</ui:define>
	
	<ui:define name="footer">
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('rdf')}">
			<h:outputText value="As RDF/XML"/>
		</h:outputLink>
		 | 
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('ttl')}">
			<h:outputText value="As TURTLE"/>
		</h:outputLink>
		|
		<h:outputLink value="#{dispatcherBean.getLinkForFormat('nt')}">
			<h:outputText value="As NT"/>
		</h:outputLink>
	</ui:define>
	
</ui:composition>

</html> 

WebContent/content_negotiation.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- do not modify -->
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<h:body>
		<f:metadata>
		    <f:event type="preRenderView" listener="#{dispatcherBean.contentNegotiation()}" />
		</f:metadata>
	</h:body>

</html>

WebContent/not_found.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	
<ui:composition template="/WEB-INF/templates/basic_template.xhtml">
	
	<ui:define name="header">
		<h:outputText value="Resource not found"/>
	</ui:define>
	<ui:define name="content">
		<h:outputText value="#{connectionBean.requestedResourceUri} does not exist"/>	
	</ui:define>
	
</ui:composition>

</html> 